# Generated by Django 5.2.15 on 2026-06-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_approved_comment_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen opcional para la publicación', null=True, upload_to='posts/', verbose_name='Imagen'),
        ),
    ]
