# Generated by Django 5.2.15 on 2026-06-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Imagen opcional para la publicación', null=True, upload_to='posts/', verbose_name='Imagen')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la imagen')),
            ],
        ),
    ]
