# Generated by Django 5.2.15 on 2026-06-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen opcional para la publicación', null=True, upload_to='fotos/', verbose_name='Imagen'),
        ),
    ]
